name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: sudo wget 'https://storage.googleapis.com/git-repo-downloads/repo' -P /usr/local/sbin/
      - run: sudo chmod +x /usr/local/sbin/repo
      - run: mkdir rom && cd rom
      - run: repo init -u https://github.com/ProjectBlaze/manifest.git -b 12.1
      - run: repo sync -c -j$(nproc --all) --force-sync --optimized-fetch --no-tags --no-clone-bundle --prune

